version: 2.1

aliases:
  - &attach_workspace
      at: ~/project
  - &persist_to_workspace
      root: ~/project
      paths: .

defaults: &defaults
  docker:
    - image: circleci/node:latest
  working_directory: ~/project

jobs:
  init:
    <<: *defaults
    steps:
      - checkout
      - run: yarn global add lerna
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: lerna init
          command: yarn lerna:init
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - ~/.cache/yarn
      - persist_to_workspace: *persist_to_workspace

  build:
    <<: *defaults
    steps:
      - attach_workspace: *attach_workspace
      - run: yarn build
      - persist_to_workspace: *persist_to_workspace

  code-lint:
    <<: *defaults
    steps:
      - attach_workspace: *attach_workspace
      - run: yarn lint

  markdown-lint:
    <<: *defaults
    steps:
      - attach_workspace: *attach_workspace
      - run: yarn lint:markdown

  spell-check:
    <<: *defaults
    steps:
      - attach_workspace: *attach_workspace
      - run: yarn check:spelling

  typecheck:
    <<: *defaults
    steps:
      - attach_workspace: *attach_workspace
      - run: yarn typecheck

  test:
    <<: *defaults
    steps:
      - attach_workspace: *attach_workspace
      - run: yarn test
      - run: node_modules/.bin/codecov -y .codecov.yml

  publish:
    <<: *defaults
    steps:
      - attach_workspace: *attach_workspace
      - run: npm config set //registry.npmjs.org/:_authToken $NODE_AUTH_TOKEN
      - run: npm whoami
      - run: yarn lerna:publish

  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace: *attach_workspace
      - run: lerna run yarn:pack
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(my-binary --version)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./releases/

workflows:
  build-and-publish:
    jobs:
      - init
      - build:
          requires:
            - init
      - code-lint:
          requires:
            - init
      - markdown-lint:
          requires:
            - init
      - spell-check:
          requires:
            - init
      - typecheck:
          requires:
            - init
            - build
      - test:
          requires:
            - build
            - code-lint
            - markdown-lint
            - spell-check
            - typecheck
      - publish:
          requires:
            - test
          filters:
            branches:
              only: master
      - publish-github-release:
          requires:
            - publish

